spleen:
	sudo reflow run -local ../../../reflow/sourmash_compute_10x.rf -num_hashes=5000 -ksizes=21,27,33,51 -protein -dna -tenx=s3://czbiohub-maca/10x_data/10X_P4_7 -output=s3://olgabot-maca/10x/sourmash_compute/ksizes=21,27,33,51_num_hashes=5000/Spleen_10X_P4_7.sig

kidney:
	sudo reflow run -local ../../../reflow/sourmash_compute_10x.rf -num_hashes=5000 -ksizes=21,27,33,51 -protein -dna -tenx=s3://czbiohub-maca/10x_data/10X_P4_5 -output=s3://olgabot-maca/10x/sourmash_compute/ksizes=21,27,33,51_num_hashes=5000/Kidney_10X_P4_5.sig
