#!/bin/bash
# NEXTFLOW TASK: fetchSRA (SRR4053157_fastq_dump)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /home/olga/code/kmer-hashing/download_sra/kidney_human_zebrafish/work/56/53ffb492c7579e3229f58e410922d1/.exitcode
  set +u
  [[ "$tee1" ]] && kill $tee1 2>/dev/null
  [[ "$tee2" ]] && kill $tee2 2>/dev/null
  [[ "$ctmp" ]] && rm -rf $ctmp || true
  docker rm $NXF_BOXID &>/dev/null || true
  exit $exit_status
}

on_term() {
    set +e
    docker kill $NXF_BOXID
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A)"
NXF_SCRATCH=''
[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /home/olga/code/kmer-hashing/download_sra/kidney_human_zebrafish/work/56/53ffb492c7579e3229f58e410922d1/.command.begin
[[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH

set +e
ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
cout=$ctmp/.command.out; mkfifo $cout
cerr=$ctmp/.command.err; mkfifo $cerr
tee .command.out < $cout &
tee1=$!
tee .command.err < $cerr >&2 &
tee2=$!
(
docker run -i -e "NXF_DEBUG=${NXF_DEBUG:=0}" -v /home/olga/code/kmer-hashing/download_sra/kidney_human_zebrafish/work/56/53ffb492c7579e3229f58e410922d1:/home/olga/code/kmer-hashing/download_sra/kidney_human_zebrafish/work/56/53ffb492c7579e3229f58e410922d1 -v "$PWD":"$PWD" -w "$PWD" --entrypoint /bin/bash  -v /mnt/pureScratch/olga/nextflow-cache/:/root/ncbi:rw -v /mnt/pureScratch/olga/sra-download/:/mnt/pureScratch/olga/sra-download/:rw   --name $NXF_BOXID pbelmann/sra-download -c "/bin/bash /home/olga/code/kmer-hashing/download_sra/kidney_human_zebrafish/work/56/53ffb492c7579e3229f58e410922d1/.command.stub"
) >$cout 2>$cerr &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
